name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:MUKMZIEuTriqc_HnQEmM1w@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:oZxB-w3rTrqBDqyQI52D8A/streams/AQAAAB0d-Tm9_kxBn8LQoLQmIx0AAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:Wr9lLCKzQcCLzYsQx673Fw@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:oZxB-w3rTrqBDqyQI52D8A/streams/AQAAAI93eTaxkESXkGbXGKNLgf4AAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json
